# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  netcoreredisapi:
    image: netcoreredisapi
    build:
      context: .
      dockerfile: NetCoreRedis/Dockerfile
    ports:
      - 5198:5198
